version: '3.1'

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: crypto_market
    ports:
      - "54321:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
